### ISSUE TITLE
SDSS linear bias values

### ISSUE THREAD

**Issue by JaimeRZP** [xC-ell/xCell#120] opened 2021-07-07 08:15 UTC
Current values do not seem to provide a good fit to data:
b_CMASS = 2.00 *np.ones(50) # https://arxiv.org/abs/1202.6057
b_LOWZ = 2.00*np.ones(50) #https://arxiv.org/abs/1401.4171
b_ELG = 1.7 *np.ones(50) # 1.7 https://arxiv.org/abs/1509.05045
#ELG: 𝑏SGC = 1.310 ± 0.020 , 𝑏NGC = 1.330 ± 0.020 https://arxiv.org/pdf/2007.09012.pdf
b_LRG = 2.3*np.ones(50) # https://arxiv.org/pdf/1607.05383.pdf

**Comment by damonge** [comment] 2021-07-28 08:09
Jaime says the problem is only with the ELG and LRG samples

**Comment by damonge** [comment] 2021-09-02 11:03
@JaimeRZP the biases look alright to me when comparing the cross-correlation with CMB lensing with the corresponding theory prediction. Here is eBOSS

![sdss_biases](https://user-images.githubusercontent.com/8809493/131832639-b6d69db2-5b84-40b6-9932-9efb7c0fd112.png)

**Comment by damonge** [comment] 2021-09-02 11:04
and here's BOSS
![boss](https://user-images.githubusercontent.com/8809493/131832781-54bd5575-24ec-46df-b4f1-a9d314af539d.png)

**Comment by damonge** [comment] 2021-09-16 14:03
Will close this. Auto-correlations being discussed in #149

**Closed by damonge** 2021-09-16 14:03 UTC
